name: Release
on:
  push:
    tags:
      - '*'
jobs:
  automate:
    runs-on: ubuntu-18.04
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: '14'
          cache: yarn
          scope: '@patrick91'
          registry-url: 'https://npm.pkg.github.com'


      - run: yarn
      - run: grunt release --skip-tests
      - run: npm publish
      - uses: tryghost/action-ghost-release@main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
